### ISSUE TITLE
Can add Gadgets to a Presentation but no warning is provided telling me they can't be configured.

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/editor-app#100]
When adding Content you are able to select a Gadget from in-app Store and add to your Playlist, but you are never given a warning that they can only be configured from previous Editor. 

Can we prevent Gadgets from appearing within in-app Store? If not, we should probably show a similar warning provided when you open an existing presentation that contains a gadget http://www.screencast.com/t/rFM2XkoM

**Comment by ByronDarlison** [comment]
@alanclayton @brianloosbrock @ezequielc @rodrigopavezi @ghislaineguerin couple of thoughts on this:

Is it possible to filter the list of products coming back from the store to just widgets? Not show gadgets at all? And if this is possible how much effort is this and who needs to be involved?

@alanclayton is implementing the above not necessary given that we will be removing deprecated content from the store come end of November? Any thoughts?

Thanks

**Comment by rodrigopavezi** [comment]
@ByronDarlison I had a look at the store api product endpoint I could not find a type attribute which could be used to differ products types such as widgets and gadgets. I will defer it to @olegrise. Would you know if that is possible? cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi thanks for checking. @olegrise @brianloosbrock @alanclayton any thoughts as to how we should approach this? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison @brianloosbrock @olegrise there is some added complexity here in that all of Cenquies content have been build as Gadgets so even if we remove ours theirs would still be showing.

**Comment by olegrise** [comment]
@ByronDarlison @rodrigopavezi @alanclayton @brianloosbrock There is nothing in the Product spreadsheet that could indicate if product is gadget or widget. One of the options we can go with is to add an extra column to the spreadsheet. Another option is to create a list of all gadget IDs and make Editor exclude them from the list (this can be done on API level I believe).

**Comment by ByronDarlison** [comment]
@rodrigopavezi @ezequielc curious, could we use whatever mechanism we use to determine if there are gadgets in an existing presentation to show our warning to also filter the list coming from the store?

@olegrise good point re. gadget id's, something else to consider too.

@brianloosbrock @robb-price is anyone working with cenique on their gadgets and the need to convert them to widgets? 

Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison We can't use the same strategy because for the warning message we check whether  the placeholder item's type is widget or not. This information comes from the loaded presentation.

But, RVA can detect it somehow. When adding Content, both widgets and gadgets are displayed and after selecting, RVA handles them in different ways. I will investigate further.

**Comment by ezequielc** [comment]
@ByronDarlison I was looking at the new editor code, and after we select Content from store, we make a call to gadgets endpoint to get additional information. At that point, we receive a `gadgetType` property, that tells if it is a Gadget or Widget. We could add a warning message then, although it is a bit late as the user already selected the gadget. @rodrigopavezi Thoughts?

**Comment by ByronDarlison** [comment]
@ezequielc is there anyway we can use that gadgets endpoint to actually filter what the user can select from? Is that doable? 

Failing that, let's just add the warning after they select.

Thanks!

**Comment by rodrigopavezi** [comment]
@ByronDarlison I believe we could not filter because we would have to call the gadget API for each store product. This would be a big overhead for the store product modal. @ezequielc thoughts? cheers

**Comment by ezequielc** [comment]
@ByronDarlison @rodrigopavezi We can retrieve multiple gadgets at the same API call, so I think it can be done. Cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi @ezequielc can you give me a points estimate for filtering versus error message? I want to make sure that we aren't investing too much on the filtering. Thanks

**Comment by ezequielc** [comment]
@ByronDarlison I would give 1 point for the warning message and 2 for filtering. Cheers.

**Comment by ByronDarlison** [comment]
@ezequielc let's just go for the warning for now. Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison Agreed. Cheers.

**Comment by rodrigopavezi** [comment]
@ghislaineguerin could you take a look at this issue. We need a warning message for when the user chooses a gadget from the store modal. What do you recommend? A popup or a message on the playlist item modal? cheers

**Comment by ghislaineguerin** [comment]
@rodrigopavezi We need to show a modal right after adding as the modal doesn't open automatically. Can we do both?

**Comment by rodrigopavezi** [comment]
@ghislaineguerin this modal opens straight away after selecting a gadget from the store modal. 
![screen shot 2015-10-09 at 3 23 11 pm](https://cloud.githubusercontent.com/assets/1659305/10769680/57df4fba-7cce-11e5-92f5-2a010ff03ecb.png)

Can't we just add a message here? cheers

**Comment by ghislaineguerin** [comment]
@rodrigopavezi is that the right image?

**Comment by rodrigopavezi** [comment]
@ghislaineguerin sorry wrong image :stuck_out_tongue_winking_eye:

**Comment by ghislaineguerin** [comment]
@rodrigopavezi yes that's what I meant by playlist modal.

**Comment by rodrigopavezi** [comment]
@ghislaineguerin strange, it should open. Did you try it on production? cheers

**Comment by ghislaineguerin** [comment]
@rodrigopavezi I'll try.

**Comment by ghislaineguerin** [comment]
@rodrigopavezi it worked. Let's only add on playlist modal.

**Comment by rodrigopavezi** [comment]
@ghislaineguerin could you help with the design for this message box? 
![screen shot 2015-10-27 at 6 18 27 pm](https://cloud.githubusercontent.com/assets/1659305/10771304/2a6c3832-7cd7-11e5-9692-22370578ecc8.png)

cheers

**Comment by ghislaineguerin** [comment]
@rodrigopavezi yes. is there a branch for this?

**Comment by ghislaineguerin** [comment]
@rodrigopavezi here's the styling http://codepen.io/ghislaineguerin/pen/ZbaWrN

**Comment by rodrigopavezi** [comment]
@ghislaineguerin awesome, thanks a mill.

**Comment by rodrigopavezi** [comment]
@ghislaineguerin @ByronDarlison @ezequielc what do you think about this warning.

![screen shot 2015-10-28 at 12 27 41 pm](https://cloud.githubusercontent.com/assets/1659305/10792922/e9ceefa0-7d75-11e5-888f-4f9daf82a681.png)

cheers

**Comment by ByronDarlison** [comment]
@ezequielc looks good. Instead of saying Gadget item can you just call it a "Gadget". And, can we give them the option to load the previous editor same way as the other warning? Is that doable? Thanks!

**Comment by ghislaineguerin** [comment]
@rodrigopavezi can "previous version" be a link to old editor?

**Comment by rodrigopavezi** [comment]
@ByronDarlison @ghislaineguerin sure, I will make the changes. cheers

**Comment by rodrigopavezi** [comment]
@ByronDarlison @ghislaineguerin what about now?

![screen shot 2015-10-28 at 2 15 10 pm](https://cloud.githubusercontent.com/assets/1659305/10794907/58bb6512-7d7e-11e5-9c71-e7cd2df39c61.png)

cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi awesome! Thanks
