### ISSUE TITLE
Placeholder Issue - 1

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/editor-app#103]
In the new editor, when a placeholder is renamed and saved a new placeholder with the name of 'ph0' is automatically generated. This placeholder has visible unchecked by default and even if this is checked before saving and publishing, any content will not show up in preview.

**Steps to replicate**

1. Add a new placeholder and change the default name from 'ph0' to 'BlueJays'
2. Save the template
3. A new placeholder named 'ph0' will appear 
4. Add content to placeholder and click the 'visible' checkbox
5. Save and preview and content will not be visible

**Comment by alex-deaconu** [comment]
@pcsandford this is now fixed as well. Please see the description for #104 for details. Thanks!
