### ISSUE TITLE
Placeholder Issue - 2

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/editor-app#104]
When a placeholder is renamed with a name already assigned to another placeholder, no warning is given and the placeholder is duplicated with an empty playlist.

**Steps to Replicate**

1. Create new placeholder and name it 'BlueJays'. Add to it the video widget playlist item.
2. Create a new placeholder and name it 'Royals'. Add to it the text widget playlist item.
3. Rename the 'Royals' placeholder to 'BlueJays' and click save. No warning is given that the name is already taken. 

A new 'BlueJays' placeholder is created and contains the playlist item from the 'Royals' placeholder, but another 'Royals' placeholder now also exists with a blank playlist.

**Comment by alex-deaconu** [comment]
@pcsandford this is now corrected in the Editor. Actually, the whole re-name process has been re-worked such that validation errors appear when trying to use a duplicate name (along with additional validation for invalid characters and blank name).

Please verify and close. Thanks!
