### ISSUE TITLE
Widgets not Saving Settings

### ISSUE THREAD

**Issue by woneal1983** [Rise-Vision/editor-app#109]
On the youtube widget which works in the old editor is now not saving its settings in the new editor. The url will save because its using the additional params for the url. The other two items are not. The Params seemed to not be saving. I also checked the developer app for mac to be sure the widget is working and everything is correct and working according to it.

**Comment by lapinnoir** [comment]
Have come across a similar issue this morning with the settings (ie Volume) for the YouTube Widget not saving/publishing on the new Editor, but working (ie save/publish) in RVA.  Have currently advised the user to switch to RVA for the time being.

**Comment by ByronDarlison** [comment]
@ezequielc could you look at this one also with the defect card you have open. Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison Sure, we will add it to the card. Cheers
