### ISSUE TITLE
Image size proportion in Editor Content modal

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/editor-app#111]
Product images are squashed at lower resolutions, and action buttons shift position based on Product Title length.
Screenshot: https://goo.gl/3Y7Olt

**Comment by ghislaineguerin** [comment]
@alex-deaconu is this merged?

**Comment by alex-deaconu** [comment]
@ghislaineguerin yup!

**Comment by ezequielc** [comment]
@ghislaineguerin @alex-deaconu Are we good to close this issue? Cheers

**Comment by alex-deaconu** [comment]
@ezequielc good by me. Thanks.
