### ISSUE TITLE
Placeholder issues in custom template 

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/editor-app#113]
User has custom template code added into the new Editor, with some elements created on the new Editor (ie Placeholders).  When the user is adding the Premium Rise Financial Table widget they are not able to view the widget data incl dummy data.

**What I've done to troubleshoot**

1. Edited the existing Placeholder by adding a new Playlist (the premium financial widget).   The change is not reflected on preview after save/publish.

2. Created a new Placeholder (with the widget) and placed it above the user's existing Placeholder and also edited the Z number.  The change is not reflected on preview after save/publish.

3. Created a new Placeholder (using another widget - the text one).  The change is reflected but it's only appearing briefly in the user's presentation.

4. Edited another Placeholder (at text based one), the change is reflected on save/publish/preview.

**What the user has done to try to troubleshoot this:**

1. Created a new presentation in the Editor and added the widget.

2. Added some of their template code from the previous presentation.

3. On save/publish/preview they report being able to see the widget.

4. When they change the Placeholder's name, they report the presentation breaking.

**Expected Results**

I expected the widget to work:

1. When added as a new Placeholder on top of an existing Placeholder.

2. When added within an existing Placeholder (in the Playlist area).

3. When the Placeholder name has been changed for the widget.

**Comment by ezequielc** [comment]
@lapinnoir I could replicate the issue. It happens whenever we add the Rise Financial Table and don't configure it. As the widget is not configured, it won't appear in the presentation preview.
It happens not only with templates, but new presentations as well, both in the new Editor and RVA.
To make it work, you need to open the widget configuration and save.

I am not sure if it is an expected behavior or an issue with this widget. @alex-deaconu  @alanclayton Thoughts? Thanks.

**Comment by alanclayton** [comment]
@ezequielc @lapinnoir  sounds like this is only occurring with the Financial Table Widget. If correct, sounds like this should actually be an issue logged in that Widgets repo.

**Comment by ezequielc** [comment]
@alanclayton I agree.
@lapinnoir can you confirm and open the issue in the Widget repo if that is the case? Thanks

**Comment by lapinnoir** [comment]
@alanclayton @ezequielc Thanks I will open this issue in the Widget repo.
