### ISSUE TITLE
Interoperability issue for HTML Widget from Editor to RVA

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/editor-app#119]
This may be the case for other deprecated content items. Scenario for HTML Widget.

1. In the new Editor create a new HTML Widget and add simple H1 and P tag content.
2. User Saves. Receives prompt about moving to RVA due to Deprecated Content.
3. User is on RVA.
4. User Saves and Previews to see a blank Presentation.
5. User creates a new HTML Widget in RVA adding simple H1 and P tag content and Saves.
6. User is able to see the HTML Widget created within RVA but not imported from Editor.

Please see attached .txt to see the difference:

[HTMLWidgetEditortoRVA-HTMLWidgetRVAOnly.txt](https://github.com/Rise-Vision/editor-app/files/24635/HTMLWidgetEditortoRVA-HTMLWidgetRVAOnly.txt)

**Comment by ezequielc** [comment]
@lapinnoir This issue was being caused due to the placeholder item type being "Widget" instead of "widget" in the new Editor. As we fixed the root cause, this issue is no longer valid. Thanks
