### ISSUE TITLE
Color picker is transparent by default

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/editor-app#120]
A lot of users are confused over background colors not showing for placeholders. Alpha value should be 1 by default

**Comment by ezequielc** [comment]
@ghislaineguerin Alpha is 1 by default currently for new placeholders. Could you detail where this issue is happening? Thanks

**Comment by ghislaineguerin** [comment]
@ezequielc I saw recordings on fullstory with this issue, I will try to reproduce.

**Comment by ghislaineguerin** [comment]
@ezequielc if you clcik on a transparent placeholder on any other presentation and then go back and add a placeholder they will all default to transparent alpha 0

**Comment by ezequielc** [comment]
@ghislaineguerin Thanks. I will have a look.

**Comment by alex-deaconu** [comment]
Fixed in the PR referenced above. Closing. Thanks.
