### ISSUE TITLE
Search keywords give wrong results

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/editor-app#122]
See attached, looking for "School" only returns banking templates.

<img width="1186" alt="screen shot 2015-11-02 at 9 40 42 am" src="https://cloud.githubusercontent.com/assets/845767/10883074/ec1887b6-8145-11e5-8d4a-1d2bc2aff2cd.png">

**Comment by ezequielc** [comment]
@olegrise I think this is related to Store, right? Thanks

**Comment by olegrise** [comment]
@ezequielc what did you expect to see?

**Comment by olegrise** [comment]
Sorry @ezequielc , I should have asked @ghislaineguerin . @ghislaineguerin is there something specific you wanted to see in results and it wasn't there?

**Comment by olegrise** [comment]
@ezequielc I just realized that search should probably return content items only. See how it's done in the Store https://github.com/Rise-Vision/store/blob/master/web/script/app.js#L383

**Comment by ghislaineguerin** [comment]
@olegrise well, I'm wondering why those results came out if they don't have the word "school" assigned to them

**Comment by ezequielc** [comment]
Thanks @olegrise . We are returning only Content when adding placeholder items. I think that search was in the Add from Template window and it is filtered by productTag = Templates. Cheers

**Comment by olegrise** [comment]
@ghislaineguerin the word "school" is there in the description of the product.

**Comment by ghislaineguerin** [comment]
@olegrise got it. thanks.

**Comment by ezequielc** [comment]
@ghislaineguerin Should we close this issue? Thanks
