### ISSUE TITLE
The artboard is bigger than the resolution

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#128]
In this GIF the artboard is set to 1920x1080 and the placeholder is set to 1920x1080 but the artboard looks about 20px bigger on the bottom and right side. 

Presentation: https://editor.risevision.com/#/editor/workspace/fa375968-9202-4563-8e6b-e89bf3d3413f/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

GIF
![artboard-bigger-than-resolution](https://cloud.githubusercontent.com/assets/9273546/10970213/324090c4-839b-11e5-9788-0fe28237f20f.gif)

**Comment by alex-deaconu** [comment]
@sheadarlison this issue is now fixed. Please verify. Thanks!

**Comment by sheadarlison** [comment]
@alex-deaconu Looks good thanks
