### ISSUE TITLE
Images don't scale in editor

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#129]
If you set a placeholder or presentation background to an image and set it to scale it does not in the editor. However, it does in preview. 

See here: https://editor.risevision.com/#/editor/workspace/2023f9dc-b2d0-4053-bf46-4abcfc969ea3/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

http://preview.risevision.com/?type=presentation&id=2023f9dc-b2d0-4053-bf46-4abcfc969ea3&showui=false

https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/image1.JPG

**Comment by alex-deaconu** [comment]
@sheadarlison this issue is now fixed. Please verify. Thanks!

**Comment by sheadarlison** [comment]
@alex-deaconu Looks good thanks
