### ISSUE TITLE
Image preview in placeholder is broken

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#130]
If you set an image background for a placeholder the little preview is incredibly small.

https://editor.risevision.com/#/editor/workspace/2023f9dc-b2d0-4053-bf46-4abcfc969ea3/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

![image-preview-to-small](https://cloud.githubusercontent.com/assets/9273546/10970383/4a208fc2-839c-11e5-8764-7753ef074c9c.gif)
![screen shot 2015-11-05 at 9 04 33 am](https://cloud.githubusercontent.com/assets/9273546/10970437/93bbec44-839c-11e5-9739-63596b4d63c7.png)

**Comment by ghislaineguerin** [comment]
@alex-deaconu This can't be fixed by styles. The image container has bootstrap grid classes that must be removed.

**Comment by alex-deaconu** [comment]
@sheadarlison updated the image preview so the size is more consistent, across all resolutions (mobile, tablet, desktop). Please take a look and let us know what you think. Thanks.

**Comment by ezequielc** [comment]
@sheadarlison Are we good to close this issue? Thanks
