### ISSUE TITLE
Weather Widget

### ISSUE THREAD

**Issue by ghammer14** [Rise-Vision/editor-app#132]
Regarding DC weather widget in the new editor,  it is failing to save the parameters and its value.

The data it is failing to save is written with the following code:
 
params = "?up_layout=" + selectedLayout.val();

Earlier when we saved this it was able to retrieve the value using prefs.getString("layout")

Now it is returning empty value.  We're seeing many of the settings (fonts, colors, menu's to those selectors, not save.

**Comment by alex-deaconu** [comment]
@ghammer14 thanks for logging this issue. It has been fixed at https://editor.risevision.com as of today; was wondering if you could verify and confirm that everything is working as expected at your end. 
Cheers!

**Comment by ghammer14** [comment]
Thank you, yes I will check on this shortly!

Gene Hamm
Partner,  Director of Sales and Marketing

DIGICHIEF | Content Innovation 
P: 859.619.4548 
digichief.com <http://www.digichief.com/> |  linkedin <http://www.linkedin.com/in/genehamm> | twitter <https://twitter.com/DIGI_TWEETS> | facebook <https://www.facebook.com/digichief> | mailing list <http://visitor.r20.constantcontact.com/d.jsp?llr=voi7ufkab&p=oi&m=1110438715861&sit=zb6dezbhb&f=20bcd467-ff36-42c2-8972-436ee439d467>
 







Confidentiality Message
This e-mail message is confidential, may be privileged and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform the sender by return e-mail immediately and delete this e-mail message and destroy all copies. Thank you.

On Nov 10, 2015, at 12:42 PM, Alex Deaconu <notifications@github.com> wrote:

@ghammer14 <https://github.com/ghammer14> thanks for logging this issue. It has been fixed at https://editor.risevision.com <https://editor.risevision.com/> as of today; was wondering if you could verify and confirm that everything is working as expected at your end. 
Cheers!
