### ISSUE TITLE
Spelling Mistake On Gadget Warning

### ISSUE THREAD

**Issue by ByronDarlison** [Rise-Vision/editor-app#135]
"support" should be supported and all button text should be Title Case. "Open with previous Editor" should be "Open With Previous Editor"

![image](https://cloud.githubusercontent.com/assets/4186315/10995261/8766600c-8449-11e5-97c1-53099c0c76a8.png)

**Comment by alex-deaconu** [comment]
This is now corrected: http://screencast.com/t/hGkMFAWbqG1T
