### ISSUE TITLE
Placeholder Negative Position

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/editor-app#141]
Don't know what I did but anyway, I used only the GUI and not the HTM editor but I've one placeholder that is stuck in top left corner.
If I try to move the placeholder, I see that the top(Y) & left(X) parameters in the left hand size are changing but the placeholder itself stay stuck. If I save the page and preview it, the placeholder stay on top left corner.
I've investigated and I see that the HTML code wrongly (as far as I know) includes a left and top position for the DIV of the placeholder (here, same issue on two DIV). The position include a minus sign (left:63-px;top:66-px) and even on the ph1 DIV includes a double minus (left:2--px). 
I've checked that this issue comes when you move a placeholder over the left or top bonduaries. The negative positioning needing a minus is not correctly managed in the DIV left and top parametrs.

**Comment by alex-deaconu** [comment]
This is now fixed. Also notified the User in the community of this fix. Thanks.
