### ISSUE TITLE
'Delete' key moves Editor back in browser history (behind modal)

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/editor-app#144]
Also happens when there is no modal. Chrome/OSX

![issue](https://cloud.githubusercontent.com/assets/11826611/11129867/c850e618-894f-11e5-96ee-c06a9145b78f.gif)

**Comment by alex-deaconu** [comment]
Moved to rise-vision-apps https://github.com/Rise-Vision/rise-vision-apps/issues/69. Closing. Thanks.
