### ISSUE TITLE
Background Images In New Editor

### ISSUE THREAD

**Issue by ghammer14** [Rise-Vision/editor-app#151]
Used the new editor to edit and play our Digichief Weather Widget that was set up from the old editor.  
I found the background image was not visible in its placeholder, but does display in preview. 

Here is a video of my results.

https://www.dropbox.com/s/51xvntdjzcbl7yf/NewEditorDC-weather.mov?dl=0

**Comment by ezequielc** [comment]
Thanks @ghammer14 ! We are going to investigate the issue.

**Comment by ezequielc** [comment]
@ghammer14 Apologies for taking so long to reply, I missed this issue somehow.
From what I can see, your presentation does not have a background. 
There is a placeholder with an Image Widget that covers the whole area and works like a background. 
At the time of your issue, Editor was not able to show images from Image Widget, you could only see them in Preview.
Currently, Editor is able to show images, so I think this issue can be closed. 
If you have any comment, please let me know. Thanks!
