### ISSUE TITLE
You can't save a Template Presentation that is opened in the new Editor from a URL

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/editor-app#152]
<b>How it works now:</b>
1. Using the <a href="https://store.risevision.com/product/111/U.S.%20Stocks%20-%20Real%20Time%20Streaming">StockTrak Real Time Stocks Widget Product</a>, open a copy of the Sample Presentation from the link at the bottom of the page (https://editor.risevision.com/#/editor/workspace/3dc8e3ae-e76a-4aaf-9f3c-fcc832987e73/fromCompanyId=f114ad26-949d-44b4-87e9-8528afc76ce4)
2. Save the Presentation. Go back to your Presentations page, notice that it has NOT saved the Presentation.

For further clarification: https://drive.google.com/open?id=0B_UegzKseBZXV2pGMWxKRmpMVlE

<b>How it should work:</b>
When you save the Presentation opened from that link, it should save the Presentation.

**Comment by ezequielc** [comment]
@robb-price the issue here is that the link is just opening the presentation instead of making a copy.

I updated the editor to support copying presentations, but the URL must be changed in Store. Links for copying presentations should be like this: https://editor.risevision.com/#/editor/workspace/new/?copyOf=b22bc4ad-4cfd-4de4-b86b-b3b5b6be1539

@olegrise Are you ok with changing the links? Thanks

**Comment by olegrise** [comment]
@ezequielc sounds good. 

@RV-Adrian could you take care of this?

**Comment by olegrise** [comment]
@RV-Adrian please disregard my comment. The data is coming from the Products spreadsheet. @robb-price do you mind fixing the URLs in there?

**Comment by robb-price** [comment]
@olegrise Yup, I will take care of this and close the issue once this is corrected.

**Comment by olegrise** [comment]
Thanks @robb-price !

**Comment by ezequielc** [comment]
@olegrise @robb-price Thanks!

**Comment by robb-price** [comment]
@olegrise @ezequielc All Products with these links have been updated in Production.

Issue is closed.

**Comment by olegrise** [comment]
@robb-price @ezequielc it looks like there is still a small problem with copying templates: [video](https://drive.google.com/file/d/0Bzdv7xpveuRlZkhQT3lNeTQzSk0/view?usp=sharing)

**Comment by ezequielc** [comment]
Thanks @olegrise I will have a look. Cheers

**Comment by ezequielc** [comment]
@olegrise We could not replicate the issue. Does it still happen if you clear the cache? Thanks

**Comment by olegrise** [comment]
@ezequielc I'm seeing the same thing in Chrome incognito mode. I'm on Mac. The strange thing is that when I resize browser (from/to full screen), the spinner disappears.

**Comment by ezequielc** [comment]
Thanks @olegrise I will investigate further.
