### ISSUE TITLE
Storage button in Background Image settings is oversized

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/editor-app#155]
Screenshot: http://goo.gl/kjgmW4

Happens in both the presentation properties modal and the sidebar

Adding `btn-widget-icon-storage` and removing the `img` child seems to set it right, but needs testing etc.

**Comment by ezequielc** [comment]
Thanks @RV-Adrian !

**Comment by RV-Adrian** [comment]
@ezequielc :+1:  !
