### ISSUE TITLE
Can't access HTML view

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#163]
How to Replicate
Create a new presentation and add a placeholders create media queries for placeholders. Click save go to design view and go back to HTML you'll be presented with a white background. 

I tried refreshing, going back to the presentations list, but it just stays with a white background.

You can see it here: https://apps.risevision.com/editor/workspace/ff3ca153-c609-4fa6-9cf9-4c2b19340d89/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

What to Expect
You can edit the HTML.

**Comment by sheadarlison** [comment]
![strange-editor-behaviour](https://cloud.githubusercontent.com/assets/9273546/11898673/a5fc869c-a567-11e5-830a-245b5322b95b.gif)

**Comment by alex-deaconu** [comment]
This issue is now fixed. Closing. Thanks.
