### ISSUE TITLE
Text Widget not being rendered in Editor

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/editor-app#165]
Add the Text Widget to an empty Placeholder, add some text then save. Notice the Text is not being rendered in Editor. As long as the Text Widget is the first item in the Playlist, the text should be rendered.

**Comment by ezequielc** [comment]
@alanclayton We merged the apps, so this repository is no longer in use. Any issues should be added to https://github.com/Rise-Vision/rise-vision-apps/. I will close the issue here and add it there. Thanks
