### ISSUE TITLE
Duration does not stay saved

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#74]
To reproduce set duration on a widget, click save, exit editor, reopen editor and go to the widget. Duration will be back at 0. 

Expected Results
Duration should stay at the selected amount.

![editor-duration-bug](https://cloud.githubusercontent.com/assets/9273546/10234997/79fd5cd0-6866-11e5-899e-3b156436413d.gif)

**Comment by ezequielc** [comment]
@sheadarlison Fixed. Thanks for reporting.
