### ISSUE TITLE
Placeholder background should be set as transparent

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#75]
Steps to reproduce:
Add placeholder in new editor

Result:
Background set to solid white

How it should work:
Background set to transparent or none

Link to Presentation:
Any presentation will have this.

OS:
Mac Yosemite 10.5

Chrome Ver:
45

![screen shot 2015-10-01 at 6 11 29 pm](https://cloud.githubusercontent.com/assets/9273546/10235145/df3d101c-6867-11e5-85bc-9a06e7f6c1c8.png)
![screen shot 2015-10-01 at 6 09 38 pm](https://cloud.githubusercontent.com/assets/9273546/10235146/df3de956-6867-11e5-8366-9b5b3dd62db0.png)

**Comment by ghislaineguerin** [comment]
@ezequielc @sheadarlison 
It makes sense that placeholders are set to transparent by default.

**Comment by ezequielc** [comment]
Fixed. Thanks @sheadarlison and @ghislaineguerin
