### ISSUE TITLE
Duration box isn't large enough to see more than one number

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#76]
Steps to reproduce:
Open a playlist item in new editor

Result:
Duration box only shows 1 number

How it should work:
Duration box shows three digits

Link to Presentation:
https://editor.risevision.com/#/editor/workspace/10ea30a8-c243-412e-9845-49795c98815b/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

OS:
Mac Yosemite 10.5

Chrome Ver:
45

![screen shot 2015-10-01 at 6 13 57 pm](https://cloud.githubusercontent.com/assets/9273546/10235178/332b961c-6868-11e5-8f0d-af5bf4be501b.png)
![screen shot 2015-10-01 at 6 14 35 pm](https://cloud.githubusercontent.com/assets/9273546/10235188/505da9a0-6868-11e5-86fb-87d0305cd171.png)

**Comment by ezequielc** [comment]
Thanks @sheadarlison . Fixed.
