### ISSUE TITLE
Presentations built in new editor will not preview

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#81]
Steps to reproduce:
Add placeholder in new editor, add content, save, attempt to preview

Result:
Preview will be white

How it should work:
Preview should work.

Link to Presentation:
https://editor.risevision.com/#/editor/workspace/16dc67d3-3a8b-485b-9584-fab07e9da5b4/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

OS:
Mac Yosemite 10.5

Chrome Ver:
45

![preview-does-not-work-2](https://cloud.githubusercontent.com/assets/9273546/10257205/f6134f56-6923-11e5-9129-9f677a8be774.gif)
![preview-does-not-work](https://cloud.githubusercontent.com/assets/9273546/10257204/f6128f58-6923-11e5-8e41-3109bfc14ed9.gif)

**Comment by ezequielc** [comment]
Fixed. Thanks @sheadarlison
