### ISSUE TITLE
Preview does not show latest widget settings.

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#88]
I'm not sure if this is an editor problem, or a Countdown Widget problem.

Steps to reproduce:
Set font size to anything, click save, click apply, click save, click preview.

Result:
Change is not reflected.

How it should work:
The font size should change

Link to Presentation:
https://editor.risevision.com/#/editor/workspace/1854a505-8610-4b8a-bf39-d982c3c30b23/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

OS:
Mac Yosemite 10.5

Chrome Ver:
45

![widget-does-not-change](https://cloud.githubusercontent.com/assets/9273546/10290393/c753bcdc-6b71-11e5-8901-3a76e52506ae.gif)

**Comment by sheadarlison** [comment]
I believe this is an editor issue. I tested with the text widget and had the same issue. 

![font-size-change](https://cloud.githubusercontent.com/assets/9273546/10290472/549d9d06-6b72-11e5-91bd-abd53678fb4d.gif)

**Comment by ezequielc** [comment]
I couldn't reproduce exactly like described, but I found the same issue when modifying widgets just after saving the presentation. Any changes made were not saved or previewed. I supposed the issues are related.

**Comment by sheadarlison** [comment]
@ezequielc I think they would be, I'll keep playing around with it. Maybe it was just a glitch.

**Comment by ezequielc** [comment]
Fixed. Thanks again @sheadarlison
