### ISSUE TITLE
You can't add Free or Premium Template Presentations using the new Editor

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/editor-app#92]
<b>How it works now:</b>
Go to the new Editor, try to add a Free or Premium Template. Notice that pressing Add does nothing. If you do this in the older Editor, Premium templates will bring up the Store so you can add it to your cart and purchase, while free templates will open in the editor when you press Add.

For further clarification: https://goo.gl/NnpqC8

<b>How it should work:</b>
Clicking Add for free template Presentations should open it in the Editor, while premium templates should open the store to allow for the payment process.

@RV-Adrian I know you had some opinions about this after watching some full story videos, do you want to weigh in on this? @brianloosbrock FYI

**Comment by RV-Adrian** [comment]
@robb-price Addendum to this, from the Store POV: http://goo.gl/XCUCc6
Will make this a separate task from this issue since it's focusing on Editor.

**Comment by alex-deaconu** [comment]
@robb-price @RV-Adrian to clarify, paid templates have not yet been implemented in the Editor (or RVA for that matter). The process so far is only designed for Free templates.

With regard to the issue at hand, not being able to add the Template, we're currently pursuing a fix for this in the Core. 

Thanks.

**Comment by rodrigopavezi** [comment]
@robb-price fix has been deployed. could you please verify? cheers

**Comment by robb-price** [comment]
@rodrigopavezi @alex-deaconu Confirmed that I can now add templates.

Issue is verified and closed.
