### ISSUE TITLE
PUD Functionality not working with Video Folder Widget

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/editor-app#93]
Original presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=7f425e76-e73e-493c-bc86-0c15fcb18734?cid=4ebf4461-1830-4ec2-a9bd-64cc32e60499

Preview: http://preview.risevision.com/Viewer.html?type=presentation&id=7f425e76-e73e-493c-bc86-0c15fcb18734

Reproduction Steps

Created a folder in storage and uploaded 2 videos
Created placeholder, implemented video folder widget
Added RSS feed to the placeholder 
In video folder configuration, selected “play until done”

Expected results: 

Each video should play until done before moving on to the next one.

Actual results:

Videos will not play at all, only the RSS feed will show. I had to manually input the duration and unselect ‘play until done’ in order for the videos to play. I tried placing the widget at the top of the playlist but still run into the same issue. 

<img width="1051" alt="screen shot 2015-10-07 at 10 48 42 am" src="https://cloud.githubusercontent.com/assets/11686685/10341135/7839ac58-6ce1-11e5-91c2-1bf3eb1469df.png">

**Comment by ByronDarlison** [comment]
@ezequielc can you review this defect and let me know your thoughts as to what is the cause here. Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison @sheadarlison In my tests, the videos were playing in loop, without calling the next placeholder item, unless I set duration.

I could not find anything wrong with the properties, and as the issue also happens in RVA, could it be something wrong with the Done event of the widget? 
@stulees FYI

**Comment by alanclayton** [comment]
@stulees can you double check that the Widget is sending the Done event? thanks

**Comment by stulees** [comment]
@alanclayton @ezequielc I've reviewed this test presentation http://rva.risevision.com/#/PRESENTATION_MANAGE/id=fee9502d-b608-4581-b806-79b2ea111183?cid=f114ad26-949d-44b4-87e9-8528afc76ce4 in preview that Ezequiel created. 

I'm not seeing any issue. The placeholder is rotating through the Text and Video Folder Widgets. The Video Folder widget instances are playing their videos and when the last video finishes, placeholder is rotating to the next Text Widget in the playlist. @ByronDarlison FYI

**Comment by alanclayton** [comment]
@stulees in what you reviewed did you confirm that PUD is working as expected? Can you get with @ezequielc and see why it is not working for him?

**Comment by stulees** [comment]
@alanclayton The Widget definitely sends the Done event when it completes its last video. I'll check in with @ezequielc again to see if he needs anything.

**Comment by ezequielc** [comment]
@stulees @alanclayton I can't replicate it anymore. I tried many times, with different folders and it is working properly. 
@sheadarlison Can you replicate the issue? Thanks

**Comment by sheadarlison** [comment]
@ezequielc @stulees @alanclayton I've had mixed results trying to replicate it. I've tried a few times and it hasn't happened again.

**Comment by sheadarlison** [comment]
@ezequielc @stulees @alanclayton I'm going to close this until I can consistently replicate the issue
