### ISSUE TITLE
Deprecated Content use old editor warning / loop

### ISSUE THREAD

**Issue by ByronDarlison** [Rise-Vision/editor-app#96]
Problem:

Opened Presentation with Gadgets / Items and received warning

Closed Presentation and opened new one

Received warning about deprecated content, this is a new presentation? hit cancel

Gave Presentation a name

Presentation name changed to "copy of undefined"

Looped here till it worked

Correction:

Open Presentation with Gadgets / Items and receive warning, be able to open anyways as I may need to edit existing widgets and I want to use new editor, in addition to opening in old editor or just cancelling

Closed Presentation and open new one - there should be no warning about deprecated content

Give Presentation a name and it does not change to copy of undefined

**Comment by ByronDarlison** [comment]
@ezequielc can you take a look at the above that I discovered and let me know your thoughts. Thanks

**Comment by ezequielc** [comment]
@ByronDarlison I could not replicate all the issues. I got the warning for a new presentation, but I could change the presentation name without any problem.

The current behavior of the the cancel button in the warning is to remain in the new editor. Your suggestion is to return to presentation list on cancel and add a third button to open in new editor, right?

Re: warning in a new presentation, it should be easy to fix. Should we work on it in the current sprint?

I will try again if I can replicate the presentation name issue. 

Cheers

**Comment by ByronDarlison** [comment]
@ezequielc 

> The current behavior of the the cancel button in the warning is to remain in the new editor. Your suggestion is to return to presentation list on cancel and add a third button to open in new editor, right?

I think I misunderstood the functionality somehow or that loop I was in was messing things up. I reset cache but still had the same problem. Not sure...

> Re: warning in a new presentation, it should be easy to fix. Should we work on it in the current sprint?

No, can you queue it up and the top of the next sprint.

> I will try again if I can replicate the presentation name issue.

Let's pick it up after this sprint and see what we can find. No point context switching, let's stay focussed on current sprint. Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison I will add a card for next sprint. Thanks!
