### ISSUE TITLE
Not all Widgets are appearing within in-app Store

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/editor-app#99]
Image Widget, and possibly others, do not appear in the scrolling list of content within in-app Store, but it can be found if you search for it using the keyword "Image'.

**Comment by ByronDarlison** [comment]
@alanclayton good catch. This is very strange. @ezequielc any idea what is happening here? FYI @brianloosbrock @olegrise @alexey-rise 

Thanks!

**Comment by rodrigopavezi** [comment]
@ByronDarlison currently, editor is just pulling the default number of entities from backend which is 40. We can increase this number to accommodate the amount of products we have but I suggest we implement something similar to the other entities such as presentation and display where it loads more entities when scrolling down. Thoughts? cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi to make this simple and given there aren't that many products, can we pull them all in? Thanks

**Comment by rodrigopavezi** [comment]
@ByronDarlison I think so. There is a limit of a 1000 entities per call to the index. It means we can retrieve maximum 1000 entities each time. If we had 2000 entities on the index we would have to make two search calls for retrieving all the data.  So, once we get more than 1000 products we will have to add something like the scrolling method I mentioned above. cheers

**Comment by ByronDarlison** [comment]
@rodrigopavezi okay. Let's just raise it to 1,000 and that will solve this for a long time to come. Thanks

**Comment by olegrise** [comment]
Just keep an eye on performance. Loading a lot of entries may cause a delay and worsen UX.

**Comment by rodrigopavezi** [comment]
@olegrise I notice that our UI has already the incremental loading implemented. The problem is that the https://store-dot-rvacore-test.appspot.com/_ah/api/store/v0.01/products is not returning a cursor. Do you know how we could fix that? cheers

**Comment by olegrise** [comment]
@rodrigopavezi I created a [card](https://trello.com/c/4QD1gcGj/767-store-products-api-does-not-return-cursor-3) for this. We will try to include this in the next sprint which starts on November 4th.

**Comment by rodrigopavezi** [comment]
@olegrise sounds good, @ByronDarlison FYI. cheers
